[package]
name = "todos-api"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.3", features = ["postgres"] }
log = "0.4"
rocket = { version = "0.5", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
